---
- name: "Sample Node container"
  hosts: localhost
  connection: local # this is required if running playbook on localhost
  vars:
    IMAGE_NAME: "{{ lookup('env', 'IMAGE_NAME') | default('Guest') }}"
  tasks:
    - name: Deploy node app container
      docker_container:
        name: nodeapp
        image: "{{ IMAGE_NAME }}"
        state: started
        ports:
          - "3000:3000"